services:
  frontend:
    build:
      context: ./mlops-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:5000
    command: npm run dev
    develop:
      watch:
        - action: sync+restart
          path: ./mlops-frontend
          target: /app
          ignore:
            - node_modules/
            - dist/
    depends_on:
      - backend
  backend:
    build:
      context: ./mlops-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo-app
      - PORT=5000
    develop:
      watch:
        - action: sync+restart
          path: ./mlops-backend
          target: /app
          ignore:
            - node_modules/
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "3001:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: